classDiagram	class Spline {	}	class Square {	}	class Rectangle {	}	class Ellipse {	}	class EntitySelection {	}	class Shape {	}	class Polygon {	}	class Circle {	}	class Entity {	}	class DataClass {	}	class _DataStore {	}Shape <|-- SplineRectangle <|-- SquareShape <|-- RectangleShape <|-- EllipseObject <|-- EntitySelectionObject <|-- ShapeShape <|-- PolygonShape <|-- CircleObject <|-- EntityObject <|-- DataClassObject <|-- _DataStore