classDiagram	class Diagram {	}	class Entity {	}	class qsd {	}	class EntitySelection {	}	class DataClass {	}	class ClassStoreDiagram {	}	class _DataStore {	}Object <|-- DiagramObject <|-- EntityObject <|-- qsdObject <|-- EntitySelectionObject <|-- DataClassObject <|-- ClassStoreDiagramObject <|-- _DataStore